import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { TextSwitch } from "@/components/textswitch/textswitch";
import { Option } from "@/components/textswitch/option/option";
import { FieldValues, SubmitHandler, useForm } from "react-hook-form";

const inter = Inter({ subsets: ["latin"] });

const onSubmit: SubmitHandler<FieldValues> = data => {
  console.log("Seleted option value", data);
};

export default function Home() {
  const { register, handleSubmit, setValue } = useForm();

  return (
    <>
      <Head>
        <title>Component Test Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <TextSwitch register={register} setValue={setValue}>
            <Option value="left">Left</Option>
            <Option value="very-long-element">Very Long Element</Option>
            <Option value="center">Center</Option>
            <Option value="right">Right</Option>
          </TextSwitch>
          <button>Submit</button>
        </form>
      </main>
    </>
  );
}
